######################################################################
# Automatically generated by qmake (2.01a) ?? 11. ??? 15:40:18 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp mainwindow.cpp mainwindow.h.cpp
